define(function () {
    return[

        "<div id='pagetitle'>",
        "<img src='/template/08_tmp_childtown/img/hk.png' width='400'>",
        "<div style='position:absolute;width:284px;height:184px;top:67px;left:55px;overflow:hidden;'>",
        "<div style='position:absolute;width:284px;height:184px;display:table;overflow:hidden;'>",
        "<div id='titlecontent' style='width:284px;height:184px;vertical-align:middle;display:table-cell;text-align:center;font-size:30px;line-height:45px;color:#555555;opacity:0;'></div>",
        "</div>",
        "</div>",
        "</div>",
        "<div id='div1'>",
        "<div id='div1h' style='display:none'>",
        "<img src='/template/08_tmp_childtown/img/hk.png'>",
        "<div class='divh'>",
        "<img id='img1h' style='position:absolute'>",
        "<span id='word1h' class='showwords'></span>",
        "</div>",
        "</div>",
        "<div id='div1v' style='display:none'>",
        "<img src='/template/08_tmp_childtown/img/sk.png'>",
        "<div class='divv'>",
        "<img id='img1v' style='position:absolute'>",
        "<span id='word1v' class='showwords'></span>",
        "</div>",
        "</div>",
        "</div>",
        "<div id='div2'>",
        "<div id='div2h' style='display:none'>",
        "<img src='/template/08_tmp_childtown/img/hk.png'>",
        "<div class='divh'>",
        "<img id='img2h' style='position:absolute'>",
        "<span id='word2h' class='showwords'></span>",
        "</div>",
        "</div>",
        "<div id='div2v' style='display:none'>",
        "<img src='/template/08_tmp_childtown/img/sk.png'>",
        "<div class='divv'>",
        "<img id='img2v' style='position:absolute'>",
        "<span id='word2v' class='showwords'></span>",
        "</div>",
        "</div>",
        "</div>",
        "<div id='div3'>",
        "<div id='div3h' style='display:none'>",
        "<img src='/template/08_tmp_childtown/img/hk.png'>",
        "<div class='divh'>",
        "<img id='img3h' style='position:absolute'>",
        "<span id='word3h' class='showwords'></span>",
        "</div>",
        "</div>",
        "<div id='div3v' style='display:none'>",
        "<img src='/template/08_tmp_childtown/img/sk.png'>",
        "<div class='divv'>",
        "<img id='img3v' style='position:absolute'>",
        "<span id='word3v' class='showwords'></span>",
        "</div>",
        "</div>",
        "</div>",
        "<div id='div4'>",
        "<div id='div4h' style='display:none'>",
        "<img src='/template/08_tmp_childtown/img/hk.png'>",
        "<div class='divh'>",
        "<img id='img4h' style='position:absolute'>",
        "<span id='word4h' class='showwords'></span>",
        "</div>",
        "</div>",
        "<div id='div4v' style='display:none'>",
        "<img src='/template/08_tmp_childtown/img/sk.png'>",
        "<div class='divv'>",
        "<img id='img4v' style='position:absolute'>",
        "<span id='word4v' class='showwords'></span>",
        "</div>",
        "</div>",
        "</div>",

        '<div id="pFQI2W33c-an-obj-1"><div><img  height="815" width="500"  src="/template/08_tmp_childtown/img/biankuang140.jpg" style="-webkit-mask-image:url(/template/08_tmp_childtown/img/biankuang140cover.png);"></div></div>',
        '<div id="pFQI2W33c-an-obj-2"><div><img  height="116" width="114"  src="/template/08_tmp_childtown/img/biankuang140_1.png"></div></div>',
        '<div id="pFQI2W33c-an-obj-3"><div><img  height="85" width="150"  src="/template/08_tmp_childtown/img/biankuang140_2.png"></div></div>',
        '<div id="pFQI2W33c-an-obj-4"><div><img  height="85" width="150"  src="/template/08_tmp_childtown/img/biankuang140_2.png"></div></div>',

    ].join("")
})