define(function () {
    return[
       '<img id="bc_img" src="/template/03_tmp_sinian/img/bg.jpg">',
       '<div id="page11h" style="display:none">',
       '<div style="position:absolute;width:368px;height:256px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img11h" style="position:absolute">',
       '<span id="word11h" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="page11s" style="display:none">',
       '<div style="position:absolute;height:368px;width:256px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img11s" style="position:absolute">',
       '<span id="word11s" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="page12h" style="display:none">',
       '<div style="position:absolute;height:262px;width:383px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img12h" style="position:absolute">',
       '<span id="word12h" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="page12s" style="display:none">',
       '<div style="position:absolute;width:262px;height:383px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img12s" style="position:absolute">',
       '<span id="word12s" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="word1">',
       '<img style="position:absolute;-webkit-animation: word1 0.8s linear infinite alternate" src="/template/03_tmp_sinian/img/Aut.png">',
       '</div>',
       '<div id="word2">',
       '<img style="position:absolute;-webkit-animation: word2 0.8s linear infinite alternate" src="/template/03_tmp_sinian/img/Aut2.png">',
       '</div>',
       '<div id="yezi" style="display:none;">',
       '<div id="yezi1">',
       '<img id="yeying" src="/template/03_tmp_sinian/img/hyy.png">',
       '<img src="/template/03_tmp_sinian/img/hy.png">',
       '</div>',
       '</div>',
       '<div id="page32h" style="display:none">',
       '<div style="position:absolute;width:354px;height:249px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img32h" style="position:absolute">',
       '<span id="word32h" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="page31h" style="display:none">',
       '<div style="position:absolute;width:354px;height:249px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img31h" style="position:absolute">',
       '<span id="word31h" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="page32s" style="display:none">',
       '<div style="position:absolute;width:247px;height:333px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img32s" style="position:absolute">',
       '<span id="word32s" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="page31s" style="display:none">',
       '<div style="position:absolute;height:354px;width:249px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img31s" style="position:absolute">',
       '<span id="word31s" class="showwords"></span>',
       '</div>',
       '</div>',
       '<img id="paper" style="display:none" src="/template/03_tmp_sinian/img/zhip.png">',
       '<img id="pan" style="display:none" src="/template/03_tmp_sinian/img/bi.png">',
       '<div id="page2s" style="display:none">',
       '<div style="position:absolute;width:397px;height:561px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img2s" style="position:absolute">',
       '<span id="word2s" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="page2h" style="display:none;">',
       '<div style="position:absolute;width:446px;height:286px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img2h" style="position:absolute">',
       '<span id="word2h" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="hudie">',
       '<img id="chishangying" src="/template/03_tmp_sinian/img/chiying01.png" style="left:-16px;top:14px;-webkit-transform-origin: 50% 100%;;opacity:0.6">',
       '<img src="/template/03_tmp_sinian/img/shenying.png" style="left:6px;top:69px;opacity:0.6">',
       '<img id="chixiaying" src="/template/03_tmp_sinian/img/chiying.png" style="left:-15px;top:90px;-webkit-transform-origin: 50% 0%;opacity:0.6">',

       '<img id="chishang" src="/template/03_tmp_sinian/img/chi01.png" style="left:0px;top:0px;-webkit-transform-origin: 50% 100%;-webkit-animation:chibang 6s linear infinite">',
       '<img src="/template/03_tmp_sinian/img/shenzi.png" style="left:22px;top:57px;">',
       '<img id="chixia" src="/template/03_tmp_sinian/img/chi.png" style="left:0px;top:78px;-webkit-transform-origin: 50% 0%;-webkit-animation:chibang 6s linear infinite">',

       '</div>',
       '<div id="page4h" style="display:none">',
       '<div style="position:absolute;width:446px;height:324px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img4h" style="position:absolute">',
       '<span id="word4h" class="showwords"></span>',
       '</div>',
       '</div>',
       '<div id="page4s" style="display:none">',
       '<div style="position:absolute;width:322px;height:495px;top:7px;left:7px;overflow:hidden;">',
       '<img id="img4s" style="position:absolute">',
       '<span id="word4s" class="showwords"></span>',
       '</div>',
       '</div>',
       '<img id="cafe" style="display:none" src="/template/03_tmp_sinian/img/coffee.png">',
       '<div id="dou1" style="display:none">',
       '<img id="dou11" src="/template/03_tmp_sinian/img/dou.png">',
       '</div>',
       '<div id="dou2" style="display:none">',
       '<img id="dou22" src="/template/03_tmp_sinian/img/dou.png">',
       '</div>',
       '<img id="qi" src="/template/03_tmp_sinian/img/qi.png">',

       '<div id="pagetitle" style="display:none;">',
       '<div id="title1">',
       '<div id="title11">',
       '<div id="pageword1"><div id="pagewordin1"><div id="pagewordin11"><div id="titleword1" style="display:table-cell;vertical-align: middle;padding:20px;"></div></div></div></div>',
       '<div id="pageword2"><div id="pagewordin2"><div id="pagewordin22"><div id="titleword2" style="display:table-cell;vertical-align: middle;padding:20px;"></div></div></div></div>',
       '</div>',
       '</div>',
       '<div id="titleline" style="background-color:#fff;position:absolute;height:3px;top:350px;width:500px;-webkit-transform-origin:0% 0%;-webkit-transform: scale(0,1)"></div>',
       '</div>'

    ].join("")
})