define(function () {
    return[

        "<img id='baby_back' src='/template/07_tmp_children/img/baby_bg.jpg'>",

        "<img src='/template/07_tmp_children/img/01.png' style='position:absolute;top:270px;left:500px;-webkit-animation:yunmove 12s linear 9s infinite'>",
        "<!--     <img src='/template/07_tmp_children/img/01.png' style='position:absolute;top:170px;left:500px;width:60px;-webkit-animation:yunmove 12s linear 6s infinite'>",
        "<img src='http://t3.qpic.cn/mblogpic/c2a810bcd970b53a2346/2000' style='position:absolute;top:210px;left:500px;width:50px;-webkit-animation:yunmove 12s linear 3s infinite'>",
        "<img src='http://t3.qpic.cn/mblogpic/c2a810bcd970b53a2346/2000' style='position:absolute;top:30px;left:500px;width:40px;-webkit-animation:yunmove 12s linear infinite'> -->",

        "<img src='/template/07_tmp_children/img/03.png' style='position:absolute;top:140px;left:150px;-webkit-transform-origin:100% 100%;-webkit-animation:qiqiumove 4s ease-in-out infinite alternate'>",
        "<img src='/template/07_tmp_children/img/04.png' style='position:absolute;top:120px;left:260px;-webkit-transform-origin:100% 100%;-webkit-animation:qiqiumove 4s ease-in-out 1s infinite alternate;-webkit-transform:rotate(-5deg)'>",

        "<div id='baby_page_0_0'>",
        "<div class='baby_div_0_0'>",
        "<img id='baby_img_0_0' style='position:absolute;'>",
        "<span id='baby_word_0_0' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_0_0' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_0_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_0_0' class='vertical_div'>",
        "<div class='vertical_box baby_div_0_0'>",
        "<img id='vertical_baby_img_0_0' style='position:absolute;'>",
        "<span id='vertical_baby_word_0_0' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_0_0' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_0_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_0_1'>",
        "<div class='baby_div_0_1'>",
        "<img id='baby_img_0_1' style='position:absolute;'>",
        "<span id='baby_word_0_1' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_0_1' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_0_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_0_1' class='vertical_div'>",
        "<div class='vertical_box baby_div_0_1'>",
        "<img id='vertical_baby_img_0_1' style='position:absolute;'>",
        "<span id='vertical_baby_word_0_1' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_0_1' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_0_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_1_0'>",
        "<div class='baby_div_1_0'>",
        "<img id='baby_img_1_0' style='position:absolute;'>",
        "<span id='baby_word_1_0' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_1_0' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_1_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_1_0' class='vertical_div'>",
        "<div class='vertical_box baby_div_1_0'>",
        "<img id='vertical_baby_img_1_0' style='position:absolute;'>",
        "<span id='vertical_baby_word_1_0' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_1_0' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_1_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_1_1'>",
        "<div class='baby_div_1_1'>",
        "<img id='baby_img_1_1' style='position:absolute;'>",
        "<span id='baby_word_1_1' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_1_1' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_1_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_1_1' class='vertical_div'>",
        "<div class='vertical_box baby_div_1_1'>",
        "<img id='vertical_baby_img_1_1' style='position:absolute;'>",
        "<span id='vertical_baby_word_1_1' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_1_1' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_1_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_2_0'>",
        "<div class='baby_div_2_0'>",
        "<img id='baby_img_2_0' style='position:absolute;'>",
        "<span id='baby_word_2_0' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_2_0' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_2_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_2_0' class='vertical_div'>",
        "<div class='vertical_box baby_div_2_0'>",
        "<img id='vertical_baby_img_2_0' style='position:absolute;'>",
        "<span id='vertical_baby_word_2_0' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_2_0' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_2_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_2_1'>",
        "<div class='baby_div_2_1'>",
        "<img id='baby_img_2_1' style='position:absolute;'>",
        "<span id='baby_word_2_1' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_2_1' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_2_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_2_1' class='vertical_div'>",
        "<div class='vertical_box baby_div_2_1'>",
        "<img id='vertical_baby_img_2_1' style='position:absolute;'>",
        "<span id='vertical_baby_word_2_1' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_2_1' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_2_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",


        "<div id='baby_page_3_0'>",
        "<div class='baby_div_3_0'>",
        "<img id='baby_img_3_0' style='position:absolute;'>",
        "<span id='baby_word_3_0' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_3_0' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_3_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_3_0' class='vertical_div'>",
        "<div class='vertical_box baby_div_3_0'>",
        "<img id='vertical_baby_img_3_0' style='position:absolute;'>",
        "<span id='vertical_baby_word_3_0' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_3_0' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_3_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_3_2'>",
        "<div class='baby_div_3_2'>",
        "<img id='baby_img_3_2' style='position:absolute;'>",
        "<span id='baby_word_3_2' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_3_2' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_3_2' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_3_2' class='vertical_div'>",
        "<div class='vertical_box baby_div_3_2'>",
        "<img id='vertical_baby_img_3_2' style='position:absolute;'>",
        "<span id='vertical_baby_word_3_2' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_3_2' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_3_2' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_3_1'>",
        "<div class='baby_div_3_1'>",
        "<img id='baby_img_3_1' style='position:absolute;'>",
        "<span id='baby_word_3_1' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_3_1' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_3_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_3_1' class='vertical_div'>",
        "<div class='vertical_box baby_div_3_1'>",
        "<img id='vertical_baby_img_3_1' style='position:absolute;'>",
        "<span id='vertical_baby_word_3_1' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_3_1' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_3_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_4_0'>",
        "<div class='baby_div_4_0'>",
        "<img id='baby_img_4_0' style='position:absolute;'>",
        "<span id='baby_word_4_0' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_4_0' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_4_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_4_0' class='vertical_div'>",
        "<div class='vertical_box baby_div_4_0'>",
        "<img id='vertical_baby_img_4_0' style='position:absolute;'>",
        "<span id='vertical_baby_word_4_0' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_4_0' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_4_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",
        
        "<div id='baby_page_4_1'>",
        "<div class='baby_div_4_1'>",
        "<img id='baby_img_4_1' style='position:absolute;'>",
        "<span id='baby_word_4_1' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_4_1' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_4_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_4_1' class='vertical_div'>",
        "<div class='vertical_box baby_div_4_1'>",
        "<img id='vertical_baby_img_4_1' style='position:absolute;'>",
        "<span id='vertical_baby_word_4_1' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_4_1' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_4_1' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_4_2'>",
        "<div class='baby_div_4_2'>",
        "<img id='baby_img_4_2' style='position:absolute;'>",
        "<span id='baby_word_4_2' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_4_2' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_4_2' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_4_2' class='vertical_div'>",
        "<div class='vertical_box baby_div_4_2'>",
        "<img id='vertical_baby_img_4_2' style='position:absolute;'>",
        "<span id='vertical_baby_word_4_2' class='showwords'>",
        "</div>",
        "<img class='vertical_border_4_2' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_4_2' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='baby_page_5_0'>",
        "<div class='baby_div_5_0'>",
        "<img id='baby_img_5_0' style='position:absolute;'>",
        "<span id='baby_word_5_0' class='showwords'></span>",
        "</div>",
        "<img class='baby_div_5_0' src='/template/07_tmp_children/img/05.png'>",
        "<!-- <img class='baby_div_5_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='position:absolute;-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<div id='vertical_baby_page_5_0' class='vertical_div'>",
        "<div class='vertical_box baby_div_5_0'>",
        "<img id='vertical_baby_img_5_0' style='position:absolute;'>",
        "<span id='vertical_baby_word_5_0' class='showwords'></span>",
        "</div>",
        "<img class='vertical_border_5_0' src='/template/07_tmp_children/img/05.png' >",
        "<!-- <img class='vertical_border_5_0' src='http://t3.qpic.cn/mblogpic/b3f2e314ed0e0dc7be0c/2000' style='-webkit-animation:diandian 0.5s linear infinite alternate'> -->",
        "</div>",

        "<img src='/template/07_tmp_children/img/07.png' style='position:absolute;width:70px;top:580px;left:500px;-webkit-animation:qiqiufei 12s linear infinite'>",
        "<img src='/template/07_tmp_children/img/08.png' style='position:absolute;width:50px;top:250px;left:500px;-webkit-animation:qiqiufei 12s 3s linear infinite'>",
        "<img src='/template/07_tmp_children/img/08.png' style='position:absolute;width:50px;top:700px;left:500px;-webkit-animation:qiqiufei 12s 9s linear infinite'>",
        "<img src='/template/07_tmp_children/img/07.png' style='position:absolute;width:70px;top:800px;left:340px;-webkit-animation:qiqiufei 12s 6s linear infinite'>",

        "<div id='pagetitle' style='position:absolute;width:410px;height:200px;top:238px;left:45px;font-size:40px;color:#B57932;overflow:hidden;opacity:0;'>",
        "<div style='position:absolute;width:410px;height:200px;top:0px;left:0px;overflow:hidden;'>",
        "<div style='position:absolute;width:410px;height:200px;display:table;overflow:hidden;'>",
        "<div id='titlecontent' style='width:410px;height:200px;vertical-align:middle;display:table-cell;text-align:center;font-size:40px;line-height:70px;'>音乐相册，打开看看！</div>",
        "</div>",
        "</div>",
        "</div>",


    ].join("")
})