define(function () {
    return[

        "<img src='/template/06_tmp_iloveu/img/bg.jpg'>",

        "<div id='page1' class='page'>",
        "<div id='div1v'>",
        "<div id='img1v'>",
        "<span id='word1v' class='showwords'></span>",
        "</div>",
        "<img class='kuang1v' src='/template/06_tmp_iloveu/img/kuang1.png'>",
        "</div>",
        "<div id='div1h'>",
        "<div id='img1h'>",
        "<span id='word1h' class='showwords'></span>",
        "</div>",
        "<img class='kuang1h' src='/template/06_tmp_iloveu/img/kuang1.png'>",
        "</div>",
        "</div>",

        "<div id='page2' class='page' style='display:none'>",
        "<div id='div21h' class='div'>",
        "<div id='img21h'>",
        "<span id='word21h' class='showwords'></span>",
        "</div>",
        "<img class='kuang21h' src='/template/06_tmp_iloveu/img/kuang21.png'>",
        "</div>",
        "<div id='div21v' class='div'>",
        "<div id='img21v'>",
        "<span id='word21v' class='showwords'></span>",
        "</div>",
        "<img class='kuang21v' src='/template/06_tmp_iloveu/img/kuang21.png'>",
        "</div>",
        "<div id='div22v' class='div'>",
        "<div id='img22v'>",
        "<span id='word22v' class='showwords'></span>",
        "</div>",
        "<img class='kuang22v' src='/template/06_tmp_iloveu/img/kuang22.png'>",
        "</div>",
        "<div id='div22h' class='div'>",
        "<div id='img22h'>",
        "<span id='word22h' class='showwords'></span>",
        "</div>",
        "<img class='kuang22h' src='/template/06_tmp_iloveu/img/kuang22.png'>",
        "</div>",
        "<img id='dai2' src='/template/06_tmp_iloveu/img/dai2.png'>",
        "</div>",

        "<div id='page3' class='page'  style='display:none'>",
        "<div id='div3v' class='div'>",
        "<div id='img3v'>",
        "<span id='word3v' class='showwords'></span>",
        "</div>",
        "<img class='kuang3v' src='/template/06_tmp_iloveu/img/kuang3.png'>",
        "<img class='dai3v' src='/template/06_tmp_iloveu/img/dai3.png'>",
        "</div>",

        "<div id='div3h' class='div'>",
        "<div id='img3h'>",
        "<span id='word3h' class='showwords'></span>",
        "</div>",
        "<img class='kuang3h' src='/template/06_tmp_iloveu/img/kuang3.png'>",
        "<img class='dai3h' src='/template/06_tmp_iloveu/img/dai3.png'>",
        "</div>",
        "<img id='en3' src='/template/06_tmp_iloveu/img/en3.png'>",
        "</div>",

        "<div id='page4' class='page' style='display:none'>",
        "<div id='div41h' class='div'>",
        "<div id='img41h'>",
        "<span id='word41h' class='showwords'></span>",
        "</div>",
        "<img class='kuang41h' src='/template/06_tmp_iloveu/img/kuang1.png'>",
        "</div>",

        "<div id='div41v' class='div'>",
        "<div id='img41v'>",
        "<span id='word41v' class='showwords'></span>",
        "</div>",
        "<img class='kuang41v' src='/template/06_tmp_iloveu/img/kuang1.png'>",
        "</div>",
        "<div id='div42v' class='div'>",
        "<div id='img42v'>",
        "<span id='word42v' class='showwords'></span>",
        "</div>",
        "<img class='kuang42v' src='/template/06_tmp_iloveu/img/kuang1.png'>",
        "</div>",
        "<div id='div42h' class='div'>",
        "<div id='img42h'>",
        "<span id='word42h' class='showwords'></span>",
        "</div>",
        "<img class='kuang42h' src='/template/06_tmp_iloveu/img/kuang1.png'>",
        "</div>",
        "<img id='dai4' src='/template/06_tmp_iloveu/img/dai4.png'>",
        "<img id='en4' src='/template/06_tmp_iloveu/img/en4.png'>",
        "</div>",

        "<div id='page5' class='page'  style='display:none'>",
        "<div id='div5h'>",
        "<div id='img5h'>",
        "<span id='word5h' class='showwords'></span>",
        "</div>",
        "<img class='kuang5h' src='/template/06_tmp_iloveu/img/kuang3.png'>",
        "</div>",
        "<div id='div5v'>",
        "<div id='img5v'>",
        "<span id='word5v' class='showwords'></span>",
        "</div>",
        "<img class='kuang5v' src='/template/06_tmp_iloveu/img/kuang3.png'>",
        "</div>",

        "<img id='dai5' src='/template/06_tmp_iloveu/img/dai5.png'>",
        "<img id='en5' src='/template/06_tmp_iloveu/img/en5.png'>",
        "</div>",

        "<div id='page6' class='page' style='display:none'>",
        "<img id='en61' src='/template/06_tmp_iloveu/img/en61.png'>",
        "<img id='en62' src='/template/06_tmp_iloveu/img/en62.png'>",

        "<div id='div61h'>",
        "<div id='img61h'>",
        "<span id='word61h' class='showwords'></span>",
        "</div>",
        "<img class='kuang61h' src='/template/06_tmp_iloveu/img/kuang21.png'>",
        "</div>",

        "<div id='div61v' class='div'>",
        "<div id='img61v'>",
        "<span id='word61v' class='showwords'></span>",
        "</div>",
        "<img class='kuang61v' src='/template/06_tmp_iloveu/img/kuang21.png'>",
        "</div>",
        "<div id='div62v' class='div'>",
        "<div id='img62v'>",
        "<span id='word62v' class='showwords'></span>",
        "</div>",
        "<img class='kuang62v' src='/template/06_tmp_iloveu/img/kuang21.png'>",
        "<img class='dai6v' src='/template/06_tmp_iloveu/img/dai6.png'>",
        "</div>",
        "<div id='div62h'>",
        "<div id='img62h'>",
        "<span id='word62h' class='showwords'></span>",
        "</div>",
        "<img class='kuang62h' src='/template/06_tmp_iloveu/img/kuang21.png'>",
        "<img class='dai6' src='/template/06_tmp_iloveu/img/dai6.png'>",
        "</div>",

        "</div>",

        "<div id='pagetitle' style='position:absolute;width:340px;height:226px;top:250px;left:80px;font-size:30px;color:#FF437F;overflow:hidden;line-height:55px;text-shadow: #fff 2px 0 0,#fff 0 2px 0,#fff -2px 0 0,#fff 0 -2px 0;font-weight: bold;opacity:0;'>",
        "<div style='position:absolute;width:340px;height:226px;top:0px;left:0px;overflow:hidden;'>",
        "<div style='position:absolute;width:340px;height:226px;display:table;overflow:hidden;'>",
        "<div id='titlecontent' style='width:340px;height:226px;vertical-align:middle;display:table-cell;text-align:center;'></div>",
        "</div>",
        "</div>",
        "</div>",

        "<img id='love520' src='/template/06_tmp_iloveu/img/520.png'>",

        "<img id='dai1' src='/template/06_tmp_iloveu/img/dai1.png'>",
        "<img id='heart1' src='/template/06_tmp_iloveu/img/11.png'>",
        "<img id='heart2' src='/template/06_tmp_iloveu/img/12.png'>",
        "<img id='heart4' src='/template/06_tmp_iloveu/img/14.png'>",
        "<img id='heart3' src='/template/06_tmp_iloveu/img/13.png'>",
        "<img id='heart5' src='/template/06_tmp_iloveu/img/15.png'>",


    ].join("")
})