/**
 * Created by 321 on 2016/5/23.
 */
define ([], function () {
    return [
        '<div id="xiangce" class="gloab_box">',
            '<div class="xc_here">',
                '<img class="xc_img" src="/img/index.jpg"  />',
                '<div class="xc_bottom">',
                    '<div class="xc_bot_name">',
                        '我的音乐相册01',
                    '</div>',
                    '<div class="xc_bot_mesg">',
                        '<span class="mesg_a">照片数量：5张</span><span class="mesg_b">2015-03-04 12:23</span>',
                    '</div>',
                    '<div class="xc_bot_btn">',
                        '<span class="btn_bj"><i class="iconfont icon-bianji"></i>编辑</span><span class="btn_sc"><i class="iconfont icon-lajitong"></i>删除</span>',
                    '</div>',
                '</div>',
            '</div>',
            '{{each data as item }}',
            '<div class="xc_here">',
            '<div class="xc_img xc_img_js" style="overflow: hidden;"><img class="" style="max-width: 100%;max-height:100%;"  src="{{item.cover}}"  /></div>',
            '<div class="xc_bottom">',
            '<div class="xc_bot_name">',
            '{{item.title}}',
            '</div>',
            '<div class="xc_bot_mesg">',
            '<span class="mesg_a">照片数量：{{item.picnum}}张</span><span class="mesg_b">{{item.createtime}}</span>',
            '</div>',
            '<div class="xc_bot_btn">',
            '<span data-id="{{item.id}}" class="btn_bj btn_edit_js"><i class="iconfont icon-bianji"></i>编辑</span><span data-id="{{item.id}}" class="btn_sc btn_delete_js"><i class="iconfont icon-lajitong"></i>删除</span>',
            '</div>',
            '</div>',
            '</div>',
            '{{/each}}',
        '</div>',
    '<div class="modal fade " style="margin-top:100px;" id="sureDeleteModal" tabindex="-1" role="dialog">',
    '<div class="modal-dialog modal-sm" role="document">',
    '<div class="modal-content">',
    '<div class="modal-header">',
    '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>',
    '<h4 class="modal-title">提示</h4>',
    '</div>',
    '<div class="modal-body">',
    ' <p>确定要删除该小记吗？</p>',
    '</div>',
    '<div class="modal-footer">',
    '    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>',
    '    <button id="noteDeleteSure" type="button" class="btn btn-primary">确定</button>',
    '</div>',
    '</div>',
    '</div>',
    '</div>',
    ].join('')
})