define(function () {
    return[
    "<img src='/template/01_tmp_shuye/img/bg1.jpg'>",
    "<img id='ye3' src='/template/01_tmp_shuye/img/ye03.png'>",
    "<img id='ye5' src='/template/01_tmp_shuye/img/ye03.png'>",
    "<img id='ye2' src='/template/01_tmp_shuye/img/ye02.png'>",
    "<img id='ye1' src='/template/01_tmp_shuye/img/ye01.png'>",
    "<img id='ye4' src='/template/01_tmp_shuye/img/ye01.png'>",

    "<div id='pagetitle'>",
    "<div id='titlemoving'>",
    "<img id='juxing' src='/template/01_tmp_shuye/img/juxing.png'>",
    "<div style='position: absolute;width: 212px;height: 238px;top: 190px;left: 85px;overflow: hidden;'>",
    "<div style='position:absolute;width:212px;height:238px;top:0px;left:0px;overflow:hidden;'>",
    "<div style='position:absolute;width:212px;height:238px;display:table;overflow:hidden;'>",
    "<div id='titlecontent' style='width:212px;height:238px;vertical-align:middle;display:table-cell;text-align:center;font-size:32px;line-height:45px;color:#3F6E08;font-weight:bold;'></div>",
    "</div>",
    "</div>",
    "</div>",

    "<div id='wenzi'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",

    "</div>",
    "</div>",

    "<div id='div1box'>",
    "<div id='div1con' class='divcon'>",
    "<div id='div1' class='divimg'>",
    "<img id='img1' style='position:absolute'>",
    "<span id='word1' class='showwords'>aaaaaaaaaa</span>",
    "</div>",
    "<div id='wenzi1_1' class='wenzi_1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",
    "<div id='wenzi1_2' class='wenzi_2'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",
    "</div>",
    "</div>",

    "<div id='div2box'>",
    "<div id='div2con' class='divcon'>",
    "<div id='div2' class='divimg'>",
    "<img id='img2' style='position:absolute'>",
    "<span id='word2' class='showwords'></span>",
    "</div>",
    "<div id='wenzi2_1' class='wenzi_1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",
    "<div id='wenzi2_2' class='wenzi_2'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",
    "</div>",
    "</div>",

    "<div id='div3box'>",
    "<div id='div3con' class='divcon'>",
    "<div id='div3' class='divimg'>",
    "<img id='img3' style='position:absolute'>",
    "<span id='word3' class='showwords'></span>",
    "</div>",
    "<div id='wenzi3_1' class='wenzi_1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",
    "<div id='wenzi3_2' class='wenzi_2'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",
    "</div>",
    "</div>",

    "<div id='div4box'>",
    "<div id='div4con' class='divcon'>",
    "<div id='div4' class='divimg'>",
    "<img id='img4' style='position:absolute'>",
    "<span id='word4' class='showwords'></span>",
    "</div>",
    "<div id='wenzi4_1' class='wenzi_1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",
    "<div id='wenzi4_2' class='wenzi_2'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui1'>",
    "<img src='/template/01_tmp_shuye/img/tui.png' class='tui2'>",
    "<img src='/template/01_tmp_shuye/img/xian.png' class='xian'>",
    "</div>",
    "</div>",
    "</div>",

    "<div id='wenzi1div'>",
    "<div id='wenzi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "</div>",
    "</div>",

    "<div id='wenzi2div'>",
    "<div id='wenzi2'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi1'>",
    "<img src='/template/01_tmp_shuye/img/chi.png' class='chi2'>",
    "<img src='/template/01_tmp_shuye/img/yan.png' class='yan'>",
    "</div>",
    "</div>",

    "<div id='ya'>",
    "<img src='/template/01_tmp_shuye/img/jing01.png'>",
    "<img id='shuye1' src='/template/01_tmp_shuye/img/ye05.png'>",
    "<img id='shuye2' src='/template/01_tmp_shuye/img/ye06.png'>",
    "</div>",

    "<img id='xing2' src='/template/01_tmp_shuye/img/xingmang.png'>",
    "<img id='xing3' src='/template/01_tmp_shuye/img/xingmang.png'>",
    "<img id='yedi' src='/template/01_tmp_shuye/img/yedi.png'>",

    "<img id='xing1' src='/template/01_tmp_shuye/img/xingmang.png'>",
    "<img id='xing4' src='/template/01_tmp_shuye/img/xingmang.png'>",

        "<div id='loadingdiv'>",
        "<div class='loadingword'>相册正在加载中<br>请稍等……</div>",
        "</div>"

    ].join('')
})