define(function () {
    return[
        '<img id="bc_img" src="/template/02_tmp_xinnian/img/bg.jpg">',
        '<div id="div1v" class="divv" style="display:none">',
        '<img id="img1v" >',
        '<span id="word1v" class="showwords"></span>',
        '</div>',
        '<div id="div1h" class="divh" style="display:none">',
        '<img id="img1h" >',
        '<span id="word1h" class="showwords"></span>',
        '</div>',

        '<div id="div2h" class="divh" style="display:none">',
        '<img id="img2h" >',
        '<span id="word2h" class="showwords"></span>',
        '</div>',
        '<div id="div2v" class="divv" style="display:none">',
        '<img id="img2v" >',
        '<span id="word2v" class="showwords"></span>',
        '</div>',

        '<div id="div3v" class="divv" style="display:none">',
        '<img id="img3v" >',
        '<span id="word3v" class="showwords"></span>',
        '</div>',
        '<div id="div3h" class="divh" style="display:none">',
        '<img id="img3h" >',
        '<span id="word3h" class="showwords"></span>',
        '</div>',

        '<div id="div4h" class="divh" style="display:none">',
        '<img id="img4h" >',
        '<span id="word4h" class="showwords"></span>',
        '</div>',
        '<div id="div4v" class="divv" style="display:none">',
        '<img id="img4v" >',
        '<span id="word4v" class="showwords"></span>',
        '</div>',

        '<div id="up1">',
        '<img src="/template/02_tmp_xinnian/img/001.png">',
        '<div id="denglong1">',
        '<img src="/template/02_tmp_xinnian/img/002.png">',
        '</div>',
        '<div id="denglong2">',
        '<img src="/template/02_tmp_xinnian/img/003.png">',
        '</div>',
        '</div>',

        '<div style="left:60px;top:254px">',
        '<img id="xin1" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '<img id="xin2" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '</div>',
        '<div style="left:176px;top:254px">',
        '<img id="xin3" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '<img id="xin4" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '</div>',
        '<div style="left:275px;top:254px">',
        '<img id="xin5" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '<img id="xin6" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '</div>',
        '<div style="left:370px;top:254px">',
        '<img id="xin7" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '<img id="xin8" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '</div>',
        '<div style="left:235px;top:575px">',
        '<img id="xin9" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '<img id="xin10" src="/template/02_tmp_xinnian/img/008.png" class="xin">',
        '</div>',

        '<div id="zi">',
        '<img id="zi2" src="/template/02_tmp_xinnian/img/013.png">',
        '<img id="zi0" src="/template/02_tmp_xinnian/img/011.png">',
        '<img id="zi1" src="/template/02_tmp_xinnian/img/012.png">',
        '<img id="zi6" src="/template/02_tmp_xinnian/img/014.png">',
        '</div>',

        '<div id="houzi">',
        '<img id="houziin" src="/template/02_tmp_xinnian/img/007.png">',
        '</div>',

        '<img id="upzi" src="/template/02_tmp_xinnian/img/xin01.png">',

        '<div id="word1">',
        '</div>',
        '<div id="pagetitle" style="position:absolute;width:410px;height:200px;top: 390px;left:45px;font-size:40px;color:#C1010D;overflow:hidden;font-weight:bold;opacity:0;">',
        '<div style="position:absolute;width:410px;height:200px;top:0px;left:0px;overflow:hidden;">',
        '<div style="position:absolute;width:410px;height:200px;display:table;overflow:hidden;">',
        '<div id="titlecontent" style="width:390px;height:200px;text-align:left;line-height:50px;"></div>',
        '</div>',
        '</div>',
        '</div>',

        '<img id="down1" src="/template/02_tmp_xinnian/img/004.png">',
        '<img id="down2" src="/template/02_tmp_xinnian/img/005.png">',

    ].join("")
})