define(function () {
    return[

        "<img src='/template/10_tmp_students/img/bg.jpg'>",
          
        "<img id='leaf1' src='/template/10_tmp_students/img/ye06.png'>",
        "<img id='camara' src='/template/10_tmp_students/img/camara.png'>",
         
        "<div id='pagetitle' style='position:absolute;width:370px;height:237px;top:300px;left:0px;opacity:0;'>",
        "<div style='position:absolute;width:300px;height:200px;overflow:hidden;display:table;left:20px;'>",
        "<div id='titlecontent' style='width:300px;height:200px;vertical-align:middle;display:table-cell;text-align:left;font-size:30px;line-height:50px;color:#626363;'></div>",
        "</div>",
        "</div>",
           
        "<div id='page1' class='page'>",
        "<div id='div1v' class='divv'>",
        "<img class='img' id='img1v'>",
        "<span id='word1v' class='showwords'></span>",
        "</div>",
        "<div id='div1h' class='divh'>",
        "<img class='img' id='img1h'>",
        "<span id='word1h' class='showwords'></span>",
        "</div>",
        "<img id='leaf2' src='/template/10_tmp_students/img/ye02.png'>",
        "</div>",
          
        "<div id='page2' class='page'>",
        "<div id='div2v' class='divv'>",
        "<img class='img' id='img2v'>",
        "<span id='word2v' class='showwords'></span>",
        "</div>",
        "<div id='div2h' class='divh'>",
        "<img class='img' id='img2h'>",
        "<span id='word2h' class='showwords'></span>",
        "</div>",
        "<div id='leaf3'>",
        "<img src='/template/10_tmp_students/img/ye05.png'>",
        "<img id='leaf31' src='/template/10_tmp_students/img/ye051.png'>",
        "</div>",
        "</div>",
           
        "<div id='page3' class='page'>",
        "<div id='div3v' class='divv'>",
        "<img class='img' id='img3v'>",
        "<span id='word3v' class='showwords'></span>",
        "</div>",
        "<div id='div3h' class='divh'>",
        "<img class='img' id='img3h'>",
        "<span id='word3h' class='showwords'></span>",
        "</div>",
        "<img id='leaf4' src='/template/10_tmp_students/img/ye04.png'>",
        "</div>",
           
        "<div id='page4' class='page'>",
        "<div id='div4v' class='divv'>",
        "<img class='img' id='img4v'>",
        "<span id='word4v' class='showwords'></span>",
        "</div>",
        "<div id='div4h' class='divh'>",
        "<img class='img' id='img4h'>",
        "<span class='showwords' id='word4h'></span>",
        "</div>",
        "<img id='leaf5' src='/template/10_tmp_students/img/ye01.png'>",
        "</div>",
           
        "<div id='page5' class='page'>",
        "<div id='div5v' class='divv'>",
        "<img class='img' id='img5v'>",
        "<span id='word5v' class='showwords'></span>",
        "</div>",
        "<div id='div5h' class='divh'>",
        "<img class='img' id='img5h'>",
        "<span id='word5h' class='showwords'></span>",
        "</div>",
        "<img id='leaf6' src='/template/10_tmp_students/img/ye03.png'>",
        "</div>",
          
        "<img id='yezi1' src='/template/10_tmp_students/img/ye061.png'>",
        "<img id='yezi2' src='/template/10_tmp_students/img/ye061.png'>",
          
        "<img id='yezi3' src='/template/10_tmp_students/img/ye021.png'>",
        "<img id='yezi4' src='/template/10_tmp_students/img/ye021.png'>",
          
        "<img id='yezi5' src='/template/10_tmp_students/img/zisu.png'>",
        "<img id='yezi6' src='/template/10_tmp_students/img/zisu.png'>",
        "<img id='yezi7' src='/template/10_tmp_students/img/zisu.png'>",
        "<img id='yezi8' src='/template/10_tmp_students/img/fenye.png'>",
         
        "<img id='xian' src='/template/10_tmp_students/img/xian.png'>",
        "<div id='letter1'></div>",
        "<div id='letter2'></div>",
        "<div id='letter3'></div>",
        "<div id='letter4'></div>",

    ].join("")
})