define(function () {
    return[
       '<img src="img/bg.jpg">',
      '<div id="page1" class="page" style="display: none;">',
        '<img id="item1-5" src="img/zi.png" style="animation: aaa_out_bounce_up 1s ease 0.6s both;">',
        '<div id="div1" style="animation: aaa_out_bounce_down 1s ease 0.6s both;">',
          '<div id="div1h" class="divbox" style="display: block;">',
            '<img id="img1h" class="img" src="img/hn_472654411800.jpeg" style="top: -35.6818px; height: 421.364px; width: 435px; left: 0px;">',
            '<span id="word1h" class="showwords"></span>',
          '</div>',
          '<div id="div1v" class="divbox" style="display: none;">',
            '<img id="img1v" class="img" src="img/hn_472654439945.jpeg" style="top: 0px; height: 500px; width: 375px; left: -4px;">',
            '<span id="word1v" class="showwords"></span>',
          '</div>',
        '</div>',

        '<img id="item1-1" src="img/hua11.png" style="animation: aaa_out_bounce_left 1s ease both;">',
        '<img id="item1-2" src="img/hua32.png" style="animation: aaa_out_bounce_right 1s ease both;">',
        '<img id="item1-3" src="img/liwu1.png" style="animation: aaa_out_bounce_down 1s ease 0.3s both;">',
        '<img id="item1-4" src="img/mao1.png" style="animation: aaa_out_bounce_right 1s ease 0.3s both;">',
      '</div>',

      '<div id="page2" class="page" style="display: none;">',
        '<img id="item2-5" src="img/zi.png" style="animation: aaa_out_bounce_down 1s ease 0.5s both;">',

        '<div id="div2" style="animation: aaa_out_bounce_up 1s ease 0.5s both;">',
          '<div id="div2h" class="divbox" style="display: block;">',
            '<img id="img2h" class="img" src="img/hn_472654422289.jpeg" style="top: 0px; height: 320px; width: 568px; left: -67px;">',
            '<span id="word2h" class="showwords"></span>',
          '</div>
          '<div id="div2v" class="divbox" style="display: none;">',
            '<img id="img2v" class="img" src="img/hn_472654439945.jpeg" style="top: 0px; height: 459px; width: 344.25px; left: -2.125px;">',
            '<span id="word2v" class="showwords"></span>',
          '</div>',
        '</div>',
        '<img id="item2-1" src="img/qiqiu.png" style="animation: aaa_out_bounce_left 1s ease 0.3s both;">',
        '<img id="item2-2" src="img/hua22.png" style="animation: aaa_out_bounce_left 1s ease both;">',
        '<img id="item2-3" src="img/liwu2.png" style="animation: aaa_out_bounce_right 1s ease 0.3s both;">',
        '<img id="item2-4" src="img/hua21.png" style="animation: aaa_out_bounce_right 1s ease both;">',
      '</div>',

      '<div id="page3" class="page" style="display: none;">',
        '<img id="item3-1" src="img/zi.png" style="animation: aaa_out_bounce_up 1s ease 0.5s both;">',

        '<div id="div3" style="animation: aaa_out_bounce_center 1s ease 0.5s both;">',
          '<div id="div3h" class="divbox" style="display: none;">',
            '<img id="img3h" class="img" src="img/hn_472654396545.jpeg" style="left: -17.8008px; width: 469.602px; height: 320px; top: 0px;">',
            '<span id="word3h" class="showwords"></span>',
          '</div>',
          '<div id="div3v" class="divbox" style="display: block;">',
            '<img id="img3v" class="img" src="img/hn_472654439945.jpeg" style="top: 0px; height: 479px; width: 359.25px; left: -4.625px;">',
            '<span id="word3v" class="showwords"></span>',
          '</div>',
        '</div>',
        '<img id="item3-2" src="img/quan2.png" style="animation: aaa_out_bounce_left 1s ease both;">',
        '<img id="item3-3" src="img/hua31.png" style="animation: aaa_out_bounce_left 1s ease both;">',
        '<img id="item3-4" src="img/liwu1.png" style="animation: aaa_out_bounce_down 1s ease both;">',
        '<img id="item3-5" src="img/hua32.png" style="animation: aaa_out_bounce_right 1s ease both;">',
        '<img id="item3-6" src="img/zhang.png" style="animation: aaa_out_bounce_right 1s ease both;">',

      '</div>',

      '<div id="page4" class="page" style="display: none;">',
        '<img id="item4-1" src="img/zi.png" style="animation: aaa_out_bounce_up 1s ease 0.6s both;">',

        '<div id="div41" style="animation: aaa_out_bounce_left 1s ease 0.6s both;">',
          '<div id="div41h" class="divbox" style="display: block;">',
            '<img id="img41h" class="img" src="img/hn_472654396545.jpeg" style="top: 0px; height: 272px; width: 399.161px; left: -17.5807px;">',
            '<span id="word41h" class="showwords"></span>',
          '</div>',
          '<div id="div41v" class="divbox" style="display: none;">',
            '<img id="img41v" class="img" src="img/hn_472654404004.jpeg" style="left: 0px; width: 281px; height: 374.667px; top: -0.833333px;">',
            '<span id="word41v" class="showwords"></span>',
          '</div>',
        '</div>',
        '<div id="div42" style="animation: aaa_out_bounce_right 1s ease 0.6s both;">',
          '<div id="div42h" class="divbox" style="display: none;">',
            '<img id="img42h" class="img" src="img/hn_472654411800.jpeg" style="top: -28.0141px; height: 339.028px; width: 350px; left: 0px;">',
            '<span id="word42h" class="showwords"></span>',
          '</div>',
          '<div id="div42v" class="divbox" style="display: block;">',
            '<img id="img42v" class="img" src="img/hn_472654404004.jpeg" style="top: 0px; height: 362px; width: 271.5px; left: -0.75px;">',
            '<span id="word42v" class="showwords"></span>',
          '</div>',
        '</div>',
        '<img id="item4-2" src="img/lihua42.png" style="animation: aaa_out_bounce_left 1s ease both;">',
        '<img id="item4-3" src="img/quan3.png" style="animation: aaa_out_bounce_down 1s ease 0.2s both;">',
        '<img id="item4-4" src="img/tang.png" style="animation: aaa_out_bounce_down 1s ease 0.4s both;">',
        '<img id="item4-5" src="img/qiqiu2.png" style="animation: aaa_out_bounce_right 1s ease 0.4s both;">',
        '<img id="item4-6" src="img/lihua2.png" style="animation: aaa_out_bounce_right 1s ease both;">',
      '</div>',

      '<div id="page5" class="page" style="display: none;">',

        '<img id="item5-3" src="img/zi.png" style="animation: aaa_out_bounce_center 1s ease 0.7s both;">',

        '<div id="div51" style="animation: aaa_out_bounce_left 1s ease 0.8s both;">',
          '<div id="div51h" class="divbox" style="display: block;">',
            '<img id="img51h" class="img" src="img/hn_472654411800.jpeg" style="top: -32.406px; height: 314.812px; width: 325px; left: 0px;">',
            '<span id="word51h" class="showwords"></span>',
          '</div>',
          '<div id="div51v" class="divbox" style="display: none;">',
            '<img id="img51v" class="img" src="img/hn_472654439945.jpeg" style="left: 0px; width: 250px; height: 333.333px; top: -0.666667px;">',
            '<span id="word51v" class="showwords"></span>',
          '</div>',
        '</div>',
        '<div id="div52" style="animation: aaa_out_bounce_right 1s ease 0.8s both;">',
          '<div id="div52h" class="divbox" style="display: block;">',
            '<img id="img52h" class="img" src="img/hn_472654422289.jpeg" style="top: 0px; height: 294px; width: 521.85px; left: -65.925px;">',
            '<span id="word52h" class="showwords"></span>',
          '</div>',
          '<div id="div52v" class="divbox" style="display: none;">',
            '<img id="img52v" class="img" src="img/hn_472654439945.jpeg" style="top: 0px; height: 387px; width: 290.25px; left: -5.125px;">',
            '<span id="word52v" class="showwords"></span>',
          '</div>',
        '</div>',
        '<img id="item5-1" src="img/hua52.png" style="animation: aaa_out_bounce_left 1s ease both;">',
        '<img id="item5-2" src="img/liwu1.png" style="animation: aaa_out_bounce_down 1s ease 0.5s both;">',
        '<img id="item5-4" src="img/hua51.png" style="animation: aaa_out_bounce_down 1s ease both;">',
        '<img id="item5-5" src="img/mao5.png" style="animation: aaa_out_bounce_up 1s ease 0.5s both;">',
        '<img id="item5-6" src="img/quan3.png" style="animation: aaa_out_bounce_up 1s ease 0.7s both;">',
      '</div>',
      '<div id="page6" class="page">',
        '<div id="div61" style="animation: aaa_out_bounce_left 1s ease 0.5s both;">',
          '<div id="div61h" class="divbox" style="display: none;">',
            '<img id="img61h" class="img" src="img/hn_472654396545.jpeg" style="left: -17.3145px; width: 400.629px; height: 273px; top: 0px;">',
            '<span id="word61h" class="showwords"></span>',
          '</div>',
          '<div id="div61v" class="divbox" style="display: block;">',
            '<img id="img61v" class="img" src="img/hn_472654439945.jpeg" style="top: 0px; height: 362px; width: 271.5px; left: -0.75px;">',
            '<span id="word61v" class="showwords"></span>',
          '</div>',
        '</div>',
        '<div id="div62" style="animation: aaa_out_bounce_right 1s ease 0.5s both;">',
          '<div id="div62h" class="divbox" style="display: block;">',
            '<img id="img62h" class="img" src="img/hn_472654396545.jpeg" style="top: 0px; height: 265px; width: 388.889px; left: -16.4444px;">',
            '<span id="word62h" class="showwords"></span>',
          '</div>',
          '<div id="div62v" class="divbox" style="display: none;">',
            '<img id="img62v" class="img" src="img/hn_472654404004.jpeg" style="left: 0px; width: 270px; height: 360px; top: 0px;">',
            '<span id="word62v" class="showwords"></span>',
          '</div>',
        '</div>',
        '<img id="item6-1" src="img/zi.png" style="animation: aaa_out_bounce_center 1s ease 0.5s both;">',
        '<img id="item6-2" src="img/lihua62.png" style="animation: aaa_out_bounce_left 1s ease 0.5s both;">',
        '<img id="item6-3" src="img/liwu1.png" style="animation: aaa_out_bounce_down 1s ease both;">',
        '<img id="item6-4" src="img/hua21.png" style="animation: aaa_out_bounce_right 1s ease 0.5s both;">',
        '<img id="item6-5" src="img/mianju.png" style="animation: aaa_out_bounce_right 1s ease both;">',

      '</div>',

      '<div id="page0" class="page" style="display: none;">',
        '<img id="zi" src="img/zi.png" style="animation: aaa_out_bounce_up 1s ease both;">',
        '<div id="pagetitle" style="position: absolute; width: 440px; height: 220px; top: 350px; left: 30px; animation: aaa_out_bounce_down 1s ease 0.5s both;">',
          '<div style="position:absolute;width:440px;height:220px;top:0px;left:0px;overflow:hidden;display:table">',
            '<div id="titlecontent" style="width:440px;height:220px;vertical-align:middle;display:table-cell;text-align:center;font-size:35px;line-height:60px;color:#ff8800;text-shadow:#fff 3px 0 0,#fff 0 3px 0,#fff -3px 0 0,#fff 0 -3px 0;">我的相册，打开看看</div>',
          '</div>',
        '</div>',
        '<img id="item0-1" src="img/lihua42.png" style="animation: aaa_out_bounce_left 1s ease 0.5s both;">',
        '<img id="item0-2" src="img/hua21.png" style="animation: aaa_out_bounce_right 1s ease 0.5s both;">',
      '</div>',
      '<div style="width: 11px; height: 11px; position: absolute; top: -50px; left: 188px; animation: fallinga 8s linear 0s infinite both; z-index: 1; background-color: rgb(198, 208, 233);"></div>',
      '<div style="width: 13px; height: 13px; position: absolute; top: -50px; left: 4px; animation: fallinga 10s linear 0.5s infinite both; z-index: 1; background-color: rgb(198, 208, 233);"></div>',
      '<div style="width: 13px; height: 13px; position: absolute; top: -50px; left: 116px; animation: fallinga 10s linear 1s infinite both; z-index: 1; background-color: rgb(248, 125, 128);"></div>',
      '<div style="width: 10px; height: 10px; position: absolute; top: -50px; left: 455px; animation: fallinga 8s linear 1.5s infinite both; z-index: 1; background-color: rgb(186, 125, 185);"></div>',
      '<div style="width: 15px; height: 15px; position: absolute; top: -50px; left: 181px; animation: fallinga 12s linear 2s infinite both; z-index: 1; background-color: rgb(248, 125, 128);"></div>',
      '<div style="width: 14px; height: 14px; position: absolute; top: -50px; left: 268px; animation: fallinga 12s linear 2.5s infinite both; z-index: 1; background-color: rgb(198, 208, 233);"></div>',
      '<div style="width: 10px; height: 10px; position: absolute; top: -50px; left: 206px; animation: fallinga 9s linear 3s infinite both; z-index: 1; background-color: rgb(248, 125, 128);"></div>',
      '<div style="width: 15px; height: 15px; position: absolute; top: -50px; left: 188px; animation: fallinga 12s linear 3.5s infinite both; z-index: 1; background-color: rgb(245, 178, 126);"></div>',
      '<div style="width: 14px; height: 14px; position: absolute; top: -50px; left: 60px; animation: fallinga 12s linear 4s infinite both; z-index: 1; background-color: rgb(248, 125, 128);"></div>',
      '<div style="width: 11px; height: 11px; position: absolute; top: -50px; left: 358px; animation: fallinga 8s linear 4.5s infinite both; z-index: 1; background-color: rgb(248, 125, 128);"></div>',
      '<div style="width: 13px; height: 13px; position: absolute; top: -50px; left: 103px; animation: fallinga 8s linear 5s infinite both; z-index: 1; background-color: rgb(186, 125, 185);"></div>',
      '<div style="width: 11px; height: 11px; position: absolute; top: -50px; left: 311px; animation: fallinga 8s linear 5.5s infinite both; z-index: 1; background-color: rgb(245, 178, 126);"></div>',
      '<div style="width: 14px; height: 14px; position: absolute; top: -50px; left: 347px; animation: fallinga 10s linear 6s infinite both; z-index: 1; background-color: rgb(186, 125, 185);"></div>',
      '<div style="width: 13px; height: 13px; position: absolute; top: -50px; left: 201px; animation: fallinga 11s linear 6.5s infinite both; z-index: 1; background-color: rgb(198, 208, 233);"></div>',
      '<div style="width: 13px; height: 13px; position: absolute; top: -50px; left: 416px; animation: fallinga 8s linear 7s infinite both; z-index: 1; background-color: rgb(245, 178, 126);"></div>',
      '<div style="width: 13px; height: 13px; position: absolute; top: -50px; left: 457px; animation: fallinga 10s linear 7.5s infinite both; z-index: 1; background-color: rgb(245, 178, 126);"></div>',
      '<div style="width: 15px; height: 15px; position: absolute; top: -50px; left: 481px; animation: fallinga 8s linear 8s infinite both; z-index: 1; background-color: rgb(198, 208, 233);"></div>',
      '<div style="width: 10px; height: 10px; position: absolute; top: -50px; left: 116px; animation: fallinga 11s linear 8.5s infinite both; z-index: 1; background-color: rgb(245, 178, 126);"></div>',
      '<div style="width: 15px; height: 15px; position: absolute; top: -50px; left: 337px; animation: fallinga 12s linear 9s infinite both; z-index: 1; background-color: rgb(248, 125, 128);"></div>',
      '<div style="width: 16px; height: 16px; position: absolute; top: -50px; left: 336px; animation: fallinga 11s linear 9.5s infinite both; z-index: 1; background-color: rgb(158, 212, 188);"></div>'

    ].join("")
})