define(function () {
    return[

        "<img src='/template/05_tmp_birthday/img/beijing.jpg'>",

        "<div id='page1' class='page'>",
        "<div id='div1h' class='divh'>",
        "<img id='img1h' class='img'>",
        "<span id='word1h' class='showwords'></span>",
        "</div>",
        "<div id='div1v' class='divv'>",
        "<img id='img1v' class='img'>",
        "<span id='word1v' class='showwords'></span>",
        "</div>",
        "</div>",

        "<div id='page2' class='page'>",
        "<div id='div2h' class='divh'>",
        "<img id='img2h' class='img'>",
        "<span id='word2h' class='showwords'></span>",
        "</div>",
        "<div id='div2v' class='divv'>",
        "<img id='img2v' class='img'>",
        "<span id='word2v' class='showwords'></span>",
        "</div>",
        "</div>",
        "<img id='ying1h' class='yingh' src='/template/05_tmp_birthday/img/ying.png'>",
        "<img id='ying1v' class='yingv' src='/template/05_tmp_birthday/img/ying.png'>",
        "<img id='ying2h' class='yingh' src='/template/05_tmp_birthday/img/ying.png'>",
        "<img id='ying2v' class='yingv' src='/template/05_tmp_birthday/img/ying.png'>",
        "<img class='cake' src='/template/05_tmp_birthday/img/dangao.png'>",
        "<img class='flag' src='/template/05_tmp_birthday/img/caiqi.png'>",
        "<img class='flag1' src='/template/05_tmp_birthday/img/caiqi.png'>",
        "<img class='ban1' src='/template/05_tmp_birthday/img/1.png'>",
        "<img class='ban2' src='/template/05_tmp_birthday/img/2.png'>",
        "<img class='ban3' src='/template/05_tmp_birthday/img/2.png'>",
        "<img class='yingzi' src='/template/05_tmp_birthday/img/yingzi.png'>",
        "<img class='yingzi1' src='/template/05_tmp_birthday/img/yingzi.png'>",
        "<img class='xin3' src='/template/05_tmp_birthday/img/xing2.png'>",
        "<img class='xin4' src='/template/05_tmp_birthday/img/xing2.png'>",
        "<img class='xin1' src='/template/05_tmp_birthday/img/xing1.png'>",
        "<img class='xin2' src='/template/05_tmp_birthday/img/xing2.png'>",
        "<img class='huo1' src='/template/05_tmp_birthday/img/huomiao.png'>",
        "<img class='huo2' src='/template/05_tmp_birthday/img/huomiao.png'>",
        "<img class='huo3' src='/template/05_tmp_birthday/img/huomiao.png'>",
        "<img class='huo4' src='/template/05_tmp_birthday/img/huomiao.png'>",



        "<div id='pagetitle' style='position: absolute;width: 500px;height: 250px;top: 266px;left: 0px;'>",
        "<div id='titlebg'>",
        "</div>",
        "<div id='heng1'>",
        "<img id='xian1' src='/template/05_tmp_birthday/img/heng.png'>",
        "</div>",
        "<div id='heng2'>",
        "<img id='xian2' src='/template/05_tmp_birthday/img/heng.png'>",
        "</div>",
        "<div id='heng3'>",
        "<img id='xian3' src='/template/05_tmp_birthday/img/heng.png'>",
        "</div>",
        "<div id='heng4'>",
        "<img id='xian4' src='/template/05_tmp_birthday/img/heng.png'>",
        "</div>",
        "<div style='position:absolute;width:344px;height:150px;top:55px;left:72px;overflow:hidden;display:table;'>",
        "<div id='titlecontent' style='width:344px;height:150px;vertical-align:middle;display:table-cell;text-align:center;font-size:27px;line-height:40px;color:#fff;'></div>",
        "</div>",
        "</div>",


    ].join("")
})